### ISSUE TITLE
HTTP 403: Forbidden while synchronising tasks

### ISSUE THREAD

**Issue by rombert** [devsprint/org.eclipse.mylyn.github#24]
What steps will reproduce the problem?
1. Create a repository for https://github.com/rombert/ereviewboard
2. Create a query which contains all issues
3. Synchronise

An error dialog pops up after a couple of seconds.. The details are below.

-- Error Details --
Date: Tue Apr 19 10:39:30 EEST 2011
Message: Unexpected error: HTTP 403: Forbidden
Severity: Error
Product: Eclipse 1.3.2.20110218-0812 (org.eclipse.epp.package.jee.product)
Plugin: org.eclipse.mylyn.github.core
Session Data:
eclipse.buildId=M20110210-1200
java.version=1.6.0_24
java.vendor=Sun Microsystems Inc.
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.jee.product -argument -no-activate-task
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.jee.product -argument -no-activate-task

Exception Stack Trace:
org.eclipse.mylyn.github.internal.PermissionDeniedException: HTTP 403: Forbidden
at org.eclipse.mylyn.github.internal.AbstractGitHubService.executeMethod(AbstractGitHubService.java:82)
at org.eclipse.mylyn.github.internal.AbstractGitHubService.executeOperation(AbstractGitHubService.java:64)
at org.eclipse.mylyn.github.internal.GitHubCommentsService.executeRetrieveComments(GitHubCommentsService.java:68)
at org.eclipse.mylyn.github.internal.GitHubCommentsService.retrieve(GitHubCommentsService.java:62)
at org.eclipse.mylyn.github.internal.GitHubTaskDataHandler.updateTaskDataWithComments(GitHubTaskDataHandler.java:250)
at org.eclipse.mylyn.github.internal.GitHubTaskDataHandler.createTaskData(GitHubTaskDataHandler.java:234)
at org.eclipse.mylyn.github.internal.GitHubRepositoryConnector.performQuery(GitHubRepositoryConnector.java:137)
at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeQueriesJob.synchronizeQuery(SynchronizeQueriesJob.java:311)
at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeQueriesJob.synchronizeQueries(SynchronizeQueriesJob.java:268)
at org.eclipse.mylyn.internal.tasks.core.sync.SynchronizeQueriesJob.run(SynchronizeQueriesJob.java:201)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

**Comment by devsprint** [comment]
The problem is caused by the limitation imposed by github on accessing the API:
"Currently we are limiting API calls to 60 per minute. This may change in the future, or possibly per user at some point, but if you try to access the API more than 60 times in a minute, it will start giving you "access denied" errors."

For each issue, I have to make 1 call to get the issue, another call to get the comments. So there are 2 calls for each issue. As soon that you have more than 30 issues in a collection, the connector will reach the limitation. I will think on this more...

**Comment by rombert** [comment]
One possible improvement is to append this information to a 403 message: 'Please note that the GitHub API limits the number of calls per minute ; Too many calls can lead to 403 messages. '

**Comment by devsprint** [comment]
I'm looking to another alternative... to use a cache, and update cache based on etag or other informations from responses from GitHub, plus throttle the connection such that I will be able to to not create more than 60 requests in a minute.
The other alternative will be to talk with GitHub guys to see if there is a way to get around this limitation.

**Comment by devsprint** [comment]
Thanks for your suggestion. That's the short term solution.

**Comment by saidimu** [comment]
Does turning off auto-synchronization help?

Perhaps also instead of fetching comments for all issues just fetch the X most-frequently/most-recently accessed?

How about also batching the requests? Or does github count the number of results per minute, as opposed to only number of requests?

**Comment by devsprint** [comment]
As far as I know, it counts number of request per minute.

BTW, Not sure if I should continue to maintain this project since GitHub has its own developed in partnership with Eclipse...
https://github.com/eclipse/egit-github

**Comment by rombert** [comment]
Perhaps you could join and contribute to that plugin?

**Comment by devsprint** [comment]
right, I'm quite busy for the moment, but July do not seem to be a busy month....
